source "https://rubygems.org"
gem 'jekyll', '~> 4.2'
group :jekyll_plugins do
  sass-embedded ,'1.62.0'
  gem "jekyll-bookshop", "2.2.2"
  gem "cloudcannon-jekyll-bookshop", "2.2.2"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak", "~> 0.3"
end
